### ISSUE TITLE
takeDropletSnapshot error

### ISSUE THREAD

**Issue by samuelfac** [toin0u/DigitalOceanV2#164]
When I try to use **takeDropletSnapshot** of **DigitalApiClient JAVA - 2.8** with Java 7, this exception occurs:

Stack:
```
com.myjeeva.digitalocean.exception.DigitalOceanException: there are currently blocking events processing for one or more of the droplets
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.evaluateResponse(DigitalOceanClient.java:1399)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.executeHttpRequest(DigitalOceanClient.java:1344)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.doPost(DigitalOceanClient.java:1306)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.perform(DigitalOceanClient.java:1263)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.takeDropletSnapshot(DigitalOceanClient.java:438)
```

**Comment by Teevio** [comment]
Hi there, since Droplet actions take time they can only be done one at a time.  This is not an issue with this codebase, but something that you will need to accommodate for in your code.  That error you are seeing is letting you know that an action is already being executed on the Droplet.  You need to actually check a Droplet's action to make sure that nothing is in progress, before you execute a new one on the droplet.

https://developers.digitalocean.com/documentation/v2/#list-actions-for-a-droplet
https://developers.digitalocean.com/documentation/v2/#droplet-actions

**Comment by GrahamCampbell** [comment]
This repo also has nothing to do with whatever java library you are using.
